### ISSUE TITLE
Optional cookie support

### ISSUE THREAD

**Issue by elbuki** [ethanent/Vaxic#3]
Hello, nice job with this framework, minimalism at it's finest.

But one question though, why do you have a dependency called `lightcookie` in this project? In my case, I don't really need to handle cookies in my projects, so I guess you could make this cookie support as an extension or plugin, so you could promote this as a dependency-free web framework.

As a workaround I just delete the line 24 and then delete the module require statement at line 5.

Thank you.

**Comment by ethanent** [comment]
Awesome! Thanks for the suggestion. lightcookie has now been made optional. Built-in cookie parsing will be removed in Vaxic v2.0.0.

**Comment by ethanent** [comment]
**Update**: As of 65d669174713bee9e260bdd66910d15076d8ba24 (release 2.0.0), lightcookie is no longer an optionalDependency of Vaxic!
